// 'use strict';
import boxen from 'boxen';
import chalk from 'chalk';
import alert from 'cli-alerts';
import enquirer from 'enquirer';
import {execa} from 'execa';
import ora from 'ora';
import path from 'path';
const {prompt, Confirm} = enquirer;
export const {green, cyan, yellow, dim, bold} = chalk;

global.green = green;
global.cyan = cyan;
global.yellow = yellow;
global.dim = dim;
global.bold = bold;
global.boxen = boxen;
global.ora = ora;
global.prompt = prompt;
global.Confirm = Confirm;
global.execa = execa;
global.path = path;
global.alert = alert;
